ARG REPOSITORY
ARG VERSION
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base

RUN \
    dpkg --add-architecture ppc64el \
    && apt-get update -qq \
    && apt-get install -y -qq \
      --no-install-recommends \
      --allow-unauthenticated \
        g++-6-powerpc64-linux-gnu \
        gcc-6-powerpc64-linux-gnu \
        crossbuild-essential-ppc64el \
        librpm-dev:ppc64el \
    && rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
