---
name: Bump golang-version to latest version
pipelineid: 'bump-golang-version-{{ requiredEnv "BRANCH" }}'

scms:
  githubConfig:
    kind: github
    spec:
      user: '{{ requiredEnv "GITHUB_ACTOR" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      owner: elastic
      repository: golang-crossbuild
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      branch: '{{ requiredEnv "BRANCH" }}'
      commitusingapi: true

actions:
  default:
    title: '[Automation] Bump Golang version to {{ source "latestGoVersion" }}'
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      automerge: true
      labels:
        - automation
        - dependencies
        - backport-skip
      description: |
        See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo{{ source "latestGoVersion" }}+label%3ACherryPickApproved) for {{ source "latestGoVersion" }}

sources:
  minor:
    name: Get minor version
    kind: shell
    transformers:
      - findsubmatch:
          pattern: '^\d+.(\d+)'
          captureindex: 1
    spec:
      command: echo {{ requiredEnv "GO_MINOR" }}

  latestGoVersion:
    name: Get Latest Go Release
    kind: githubrelease
    dependson:
      - minor
    transformers:
      - trimprefix: go
    spec:
      owner: golang
      repository: go
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      versionfilter:
        kind: regex
        pattern: go1\.{{ source "minor" }}(\.(\d*))?$

conditions:
  dockerTag:
    name: Is docker image golang:{{ source "latestGoVersion" }} published
    kind: dockerimage
    spec:
      image: golang
      tag: '{{ source "latestGoVersion" }}'
    sourceid: latestGoVersion
## As long as there is a bug see https://github.com/updatecli/updatecli/issues/1849
## Let's use the shell kind rather than the file kind.
## When fixed then uncomment the code and remove is-already-updated
#  is:
#    name: Is version '{{ source "latestGoVersion" }}' not updated in 'go/Makefile.common'?
#    disablesourceinput: true
#    kind: file
#    spec:
#      file: go/Makefile.common
#      line: 5
#      content: VERSION        := {{ source `latestGoVersion` }}
#    failwhen: true
  is-already-updated:
    name: Is version '{{ source "latestGoVersion" }}' not updated in 'go/Makefile.common'?
    disablesourceinput: true
    kind: shell
    spec:
      command: grep 'VERSION        := {{ source `latestGoVersion` }}' go/Makefile.common && exit 1 || exit 0
    failwhen: false

targets:
  update-go-version:
    name: "Update .go-version"
    sourceid: latestGoVersion
    scmid: githubConfig
    kind: file
    spec:
      content: '{{ source "latestGoVersion" }}'
      file: .go-version
      matchpattern: '\d+.\d+.\d+'
  update-go-makefile.common:
    name: "Update go/Makefile.common"
    sourceid: latestGoVersion
    scmid: githubConfig
    kind: file
    spec:
      content: '{{ source "latestGoVersion" }}'
      file: go/Makefile.common
      matchpattern: '\d+.\d+.\d+'
  update-go-versions:
    name: 'Update go version {{ source "latestGoVersion" }}'
    kind: shell
    sourceid: latestGoVersion
    scmid: githubConfig
    spec:
      command: .github/updatecli.d/bump-go-release-version.sh
      environments:
        - name: PATH
