---
name: Bump golang-microsoft to latest version
pipelineid: 'bump-golang-microsoft-version-{{ requiredEnv "BRANCH" }}'

scms:
  githubConfig:
    kind: github
    spec:
      user: '{{ requiredEnv "GITHUB_ACTOR" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      owner: elastic
      repository: golang-crossbuild
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      branch: '{{ requiredEnv "BRANCH" }}'
      commitusingapi: true

actions:
  default:
    title: '[Automation] Bump Microsoft version to {{ source "latestGoVersion" }}'
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      automerge: true
      labels:
        - automation
        - dependencies
        - backport-skip
      description: |
        See https://github.com/microsoft/go/releases/v{{ source "latestGoVersion" }}

sources:
  minor:
    name: Get minor version
    kind: shell
    transformers:
      - findsubmatch:
          pattern: '^\d+.(\d+)'
          captureindex: 1
    spec:
      command: echo {{ requiredEnv "GO_MINOR" }}

  latestGoVersion:
    name: Get Latest Go Release
    kind: githubrelease
    dependson:
      - minor
    transformers:
      - trimprefix: v
    spec:
      owner: microsoft
      repository: go
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      versionfilter:
        kind: regex
        pattern: v1\.{{ source "minor" }}\.(\d*)-(\d*)$

  security:
    name: Get security version
    dependson:
      - latestGoVersion
    kind: shell
    transformers:
      - findsubmatch:
          pattern: '^1.{{ source "minor" }}.\d+-(\d+)'
          captureindex: 2
    spec:
      command: echo {{ source "latestGoVersion" }}

conditions:
  is-already-updated:
    name: Is security version '{{ source "security" }}' not updated in 'go/base/Dockerfile.tmpl'?
    disablesourceinput: true
    kind: shell
    spec:
      command: grep 'ARG SECURITY_VERSION={{ source `security` }}' go/base/Dockerfile.tmpl && exit 1 || exit 0
    failwhen: false

targets:
  update-go-versions:
    name: 'Update go version {{ source "latestGoVersion" }}'
    kind: shell
    sourceid: latestGoVersion
    scmid: githubConfig
    spec:
      command: .github/updatecli.d/bump-go-microsoft-version.sh
      environments:
        - name: PATH
