---
name: Bump golang-version to latest version
pipelineid: 'bump-golang-version-{{ requiredEnv "BRANCH" }}'

scms:
  githubConfig:
    kind: github
    spec:
      user: '{{ requiredEnv "GITHUB_ACTOR" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      owner: elastic
      repository: golang-crossbuild
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      branch: '{{ requiredEnv "BRANCH" }}'
      commitusingapi: true

actions:
  default:
    title: '[Automation] Bump Golang version to {{ source "latestMicrosoftGoVersion" }}'
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      automerge: false
      labels:
        - automation
        - dependencies
        - backport-skip
      description: |
        See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo{{ source "golangVersion" }}+label%3ACherryPickApproved) for {{ source "golangVersion" }}

sources:
  minor:
    name: Get minor version
    kind: shell
    transformers:
      - findsubmatch:
          pattern: '^\d+.(\d+)'
          captureindex: 1
    spec:
      command: echo {{ requiredEnv "GO_MINOR" }}

  latestMicrosoftGoVersion:
    name: Get Latest Microsoft Go Release
    kind: githubrelease
    dependson:
      - minor
    transformers:
      - trimprefix: v
    spec:
      owner: microsoft
      repository: go
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      versionfilter:
        kind: regex
        pattern: v1\.{{ source "minor" }}\.(\d*)(-\d*)$

  golangVersion:
    # NOTE: FIPS images need the Microsoft version.
    name: Get the Microsoft version of Golang, as it comes out a little later
    dependson:
      - latestMicrosoftGoVersion
    kind: shell
    transformers:
      - findsubmatch:
          pattern: '^(\d+.\d+.\d+)-(\d+)'
          captureindex: 1
    spec:
      command: echo {{ source "latestMicrosoftGoVersion" }}

conditions:
  dockerTag:
    name: Is docker image golang:{{ source "golangVersion" }} published
    kind: dockerimage
    spec:
      image: golang
      tag: '{{ source "golangVersion" }}'
    sourceid: golangVersion
  is:
    name: Is version '{{ source "golangVersion" }}' not updated in 'go/Makefile.common'?
    disablesourceinput: true
    scmid: githubConfig
    kind: file
    spec:
      file: go/Makefile.common
      line: 5
      content: VERSION        := {{ source `golangVersion` }}
    failwhen: true

targets:
  update-go-version:
    name: "Update .go-version"
    sourceid: golangVersion
    scmid: githubConfig
    kind: file
    spec:
      content: '{{ source "golangVersion" }}'
      file: .go-version
      matchpattern: '\d+.\d+.\d+'
  update-go-makefile.common:
    name: "Update go/Makefile.common"
    sourceid: golangVersion
    scmid: githubConfig
    kind: file
    spec:
      content: '{{ source "golangVersion" }}'
      file: go/Makefile.common
      matchpattern: '\d+.\d+.\d+'
  update-go-versions:
    name: 'Update go version {{ source "latestMicrosoftGoVersion" }}'
    kind: shell
    sourceid: latestMicrosoftGoVersion
    scmid: githubConfig
    spec:
      command: .github/updatecli.d/bump-go-version.sh
      environments:
        - name: PATH
