---
name: Bump golang-microsoft to latest version
pipelineid: 'bump-golang-version-{{ requiredEnv "BRANCH" }}'

scms:
  githubConfig:
    kind: github
    spec:
      user: '{{ requiredEnv "GITHUB_ACTOR" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      owner: elastic
      repository: golang-crossbuild
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      branch: '{{ requiredEnv "BRANCH" }}'
      commitusingapi: true

actions:
  default:
    title: '[Automation] Bump Microsoft version to {{ source "latestGoVersion" }}'
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      automerge: true
      labels:
        - automation
        - dependencies
        - backport-skip
      description: |
        See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo{{ source "latestGoVersion" }}+label%3ACherryPickApproved) for {{ source "latestGoVersion" }}

sources:
  minor:
    name: Get minor version
    kind: shell
    transformers:
      - findsubmatch:
          pattern: '^\d+.(\d+)'
          captureindex: 1
    spec:
      command: echo {{ requiredEnv "GO_MINOR" }}

  latestGoVersion:
    name: Get Latest Go Release
    kind: githubrelease
    dependson:
      - minor
    transformers:
      - trimprefix: v
    spec:
      owner: microsoft
      repository: go
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      versionfilter:
        kind: regex
        pattern: v1\.{{ source "minor" }}\.(\d*)-(\d*)$

targets:
  update-go-versions:
    name: 'Update go version {{ source "latestGoVersion" }}'
    kind: shell
    sourceid: latestGoVersion
    scmid: githubConfig
    spec:
      command: .github/updatecli.d/bump-go-microsoft-version.sh
      environments:
        - name: PATH
