IMAGES         := base main darwin arm armhf armel mips mips32 ppc s390x darwin-arm64
DEBIAN_VERSION := 10
TAG_EXTENSION  := -debian10

export DEBIAN_VERSION TAG_EXTENSION

build:
	@$(foreach var,$(IMAGES),$(MAKE) -C $(var) build || exit 1;)

# Requires login at https://docker.elastic.co:7000/.
push:
	@$(foreach var,$(IMAGES),$(MAKE) -C $(var) push || exit 1;)

.PHONY: build push
