ARG REPOSITORY
ARG VERSION
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base

RUN \
    dpkg --add-architecture ppc64 \
    && apt-get update -qq \
    && apt-get install -y -qq \
      --no-install-recommends \
      --allow-unauthenticated \
        g++-powerpc64-linux-gnu \
        gcc-powerpc64-linux-gnu \
        dpkg-cross \
        # FIXME install from sources \
        # librpm-dev:ppc64 \
        # libc-dev:ppc64 \
        # libpopt-dev:ppc64 \
        # linux-libc-dev:ppc64 \
        # libxml2-dev:ppc64 \
        # libxml2:ppc64 \
        # libicu-dev:ppc64 \
        # libicu57:ppc64 \
        # icu-devtools:ppc64 \
        # libsystemd-dev:ppc64 \
    && rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && powerpc64-linux-gnu-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'PowerPC64' \
  && readelf -h helloWorld | grep -c 'ELF64' \
  && readelf -h helloWorld | grep -c "big endian" \
  && rm helloWorld.c helloWorld

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
