ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN dpkg --add-architecture arm64 \
    && apt update -y --no-install-recommends \
    && apt upgrade -y --no-install-recommends \
    && apt full-upgrade -y --no-install-recommends \
    && apt install -qq -y --no-install-recommends \
        crossbuild-essential-arm64 \
        linux-libc-dev-arm64-cross

RUN apt install -qq -y \
        libc-dev:arm64 \
        libpopt-dev:arm64 \
        linux-libc-dev:arm64

{{if eq .DEBIAN_VERSION "9"}}
# librpm-dev
RUN apt install -y \
        librpm-dev:arm64 \
        librpm3:arm64 \
        librpmio3:arm64 \
        librpmbuild3:arm64 \
        librpmsign3:arm64 \
        libxml2-dev:arm64 \
        libsqlite3-dev:arm64 \
        libnss3:arm64 \
        libsqlite3-0:arm64 \
        libxml2:arm64 \
        libsqlite3-0:arm64

# libsystemd-dev
RUN apt install -y \
        libsystemd-dev:arm64 libsystemd0:arm64 liblz4-1:arm64
{{ end }}

{{if eq .DEBIAN_VERSION "10"}}
# librpm-dev
RUN apt install -y \
        librpm-dev:arm64

# libsystemd-dev
RUN apt install -y \
        libsystemd-dev:arm64
{{ end }}

RUN rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && aarch64-linux-gnu-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && file helloWorld | cut -d "," -f 2 | grep -c 'ARM aarch64'\
  && rm helloWorld.c helloWorld

RUN cd /libpcap/libpcap-1.8.1 \
	&& ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no --host=aarch64-unknown-linux-gnu --with-pcap=linux \
	&& make

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
