ARG REPOSITORY
ARG VERSION
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base

RUN \
    dpkg --add-architecture mips64el \
    && apt-get update -qq \
    && apt-get install -qq -y \
      --no-install-recommends \
      --allow-unauthenticated \
        dpkg-cross \
        gcc-mips64el-linux-gnuabi64 \
        g++-mips64el-linux-gnuabi64 \
        librpm-dev:mips64el \
        libc-dev:mips64el \
        libpopt-dev:mips64el \
        linux-libc-dev:mips64el \
        libxml2-dev:mips64el \
        libxml2:mips64el \
        libicu-dev:mips64el \
        libicu57:mips64el \
        icu-devtools:mips64el \
        libsystemd-dev:mips64el \
    && rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && mips64el-linux-gnuabi64-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'MIPS R3000' \
  && readelf -h helloWorld | grep -c 'ELF64' \
  && readelf -h helloWorld | grep -c "little endian" \
  && rm helloWorld.c helloWorld

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
