ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN \
    apt-get -o Acquire::Check-Valid-Until=false update \
    && apt-get install -qq -y --no-install-recommends --allow-unauthenticated \
        clang \
        llvm \
        cmake \
        patch \
{{- if and (ne .DEBIAN_VERSION "10") (ne .DEBIAN_VERSION "11")}}
        python \
{{- end }}
        libssl-dev \
        libxml2-dev \
        lzma-dev \
        llvm-dev \
        uuid-dev \
    && rm -rf /var/lib/apt/lists/*

{{- if or (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11")}}
ARG OSX_VERSION_MIN=10.10
{{- else }}
ARG OSXCROSS_SDK_URL=https://storage.googleapis.com/obs-ci-cache/beats/MacOSX10.11.sdk.tar.xz
ARG OSXCROSS_PATH=/usr/osxcross
ARG OSXCROSS_REV=3034f7149716d815bc473d0a7b35d17e4cf175aa
ARG SDK_VERSION=10.11
ARG DARWIN_VERSION=15
ARG OSX_VERSION_MIN=10.10
{{- end }}

RUN \
    mkdir -p /tmp/osxcross && cd /tmp/osxcross \
    && curl -sSL "https://codeload.github.com/tpoechtrager/osxcross/tar.gz/${OSXCROSS_REV}" \
        | tar -C /tmp/osxcross --strip=1 -xzf - \
    && curl -sSLo "tarballs/MacOSX${SDK_VERSION}.sdk.tar.xz" "${OSXCROSS_SDK_URL}" \
    && UNATTENDED=yes ./build.sh >/dev/null \
    && mv target "${OSXCROSS_PATH}" \
    && rm -rf /tmp/osxcross "/usr/osxcross/SDK/MacOSX${SDK_VERSION}.sdk/usr/share/man"

ENV PATH $OSXCROSS_PATH/bin:$PATH
# Add osxcross libraries to the library PATH
ENV LD_LIBRARY_PATH /usr/osxcross/lib:$LD_LIBRARY_PATH

COPY rootfs /

# Basic test
RUN cd / \
  && o64-clang helloWorld.c -o helloWorld \
  && file helloWorld \
  && file helloWorld | grep -c 'Mach-O 64-bit x86_64'

# MacOSX10.14 SDK does not have 32bits compiler
{{- if and (ne .DEBIAN_VERSION "10") (ne .DEBIAN_VERSION "11")}}
RUN cd / \
  && o32-clang helloWorld.c -o helloWorld \
  && file helloWorld \
  && file helloWorld | grep -c 'Mach-O i386' \
  && rm helloWorld.c helloWorld
{{- end }}

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
