ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''

{{- if or (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11")}}
FROM --platform=linux/amd64  docker.elastic.co/beats-dev/golang-crossbuild:llvm-apple-debian{{ .DEBIAN_VERSION }}-amd64 AS build-llvm-apple-amd64
FROM --platform=linux/arm64  docker.elastic.co/beats-dev/golang-crossbuild:llvm-apple-debian{{ .DEBIAN_VERSION }}-arm64 AS build-llvm-apple-arm64
# workaround to https://github.com/moby/moby/issues/34482
ARG TARGETARCH=amd64
ARG BUILDARCH=amd64
FROM build-llvm-apple-${TARGETARCH} as build-llvm-apple
ARG TARGETARCH
ARG BUILDARCH
RUN echo "Building ${TARGETARCH} on a ${BUILDARCH}"
{{- end }}
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN \
    apt-get -o Acquire::Check-Valid-Until=false update \
    && apt-get install -qq -y --no-install-recommends --allow-unauthenticated \
        clang \
        llvm \
        cmake \
        patch \
{{- if and (ne .DEBIAN_VERSION "10") (ne .DEBIAN_VERSION "11")}}
        python \
{{- end }}
        libssl-dev \
        libxml2-dev \
        lzma-dev \
        llvm-dev \
        uuid-dev \
    && rm -rf /var/lib/apt/lists/*

{{- if or (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11")}}
ARG OSXCROSS_PATH=/usr/local/osxcross
COPY --from=build-llvm-apple /osxcross.tar.gz /tmp/osxcross.tar.gz
RUN tar -xzf /tmp/osxcross.tar.gz -C / \
  && rm /tmp/osxcross.tar.gz
{{- else }}
ARG OSXCROSS_SDK_URL=https://storage.googleapis.com/obs-ci-cache/beats/MacOSX10.11.sdk.tar.xz
ARG OSXCROSS_PATH=/usr/osxcross
ARG OSXCROSS_REV=3034f7149716d815bc473d0a7b35d17e4cf175aa
ARG SDK_VERSION=10.11
ARG DARWIN_VERSION=15
ARG OSX_VERSION_MIN=10.10
RUN \
    mkdir -p /tmp/osxcross && cd /tmp/osxcross \
    && curl -sSL "https://codeload.github.com/tpoechtrager/osxcross/tar.gz/${OSXCROSS_REV}" \
        | tar -C /tmp/osxcross --strip=1 -xzf - \
    && curl -sSLo "tarballs/MacOSX${SDK_VERSION}.sdk.tar.xz" "${OSXCROSS_SDK_URL}" \
    && UNATTENDED=yes ./build.sh >/dev/null \
    && mv target "${OSXCROSS_PATH}" \
    && rm -rf /tmp/osxcross "/usr/osxcross/SDK/MacOSX${SDK_VERSION}.sdk/usr/share/man"
{{- end }}

ENV PATH $PATH:$OSXCROSS_PATH/bin
# Add osxcross libraries to the library PATH
ENV LD_LIBRARY_PATH $OSXCROSS_PATH/lib:/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH

COPY rootfs /

# Basic test
RUN cd / \
  && o64-clang helloWorld.c -o helloWorld.x86_64 \
  && file helloWorld.x86_64 \
  && file helloWorld.x86_64 | grep -c 'Mach-O 64-bit x86_64'

{{- if or (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11")}}
RUN cd / \
  && oa64-clang helloWorld.c -o helloWorld.arm64 \
  && file helloWorld.arm64 \
  && file helloWorld.arm64 | grep -c 'Mach-O 64-bit arm64'

RUN cd / \
  && lipo -create -output helloWorld.universal helloWorld.x86_64 helloWorld.arm64 \
  && file helloWorld.universal | grep 'Mach-O universal binary' \
  && rm helloWorld.*
{{- end }}

# MacOSX10.14 SDK does not have 32bits compiler
{{- if and (ne .DEBIAN_VERSION "10") (ne .DEBIAN_VERSION "11")}}
RUN cd / \
  && o32-clang helloWorld.c -o helloWorld.i368 \
  && file helloWorld.i368 \
  && file helloWorld.i368 | grep -c 'Mach-O i386' \
  && rm helloWorld.*
{{- end }}

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
