# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_GVM_VERSION: "v0.5.1"
  IMAGE_UBUNTU_X86_64: "family/core-ubuntu-2204"
  DOCKER_REGISTRY: "docker.elastic.co"
  STAGING_IMAGE: "${DOCKER_REGISTRY}/observability-ci"
  DOCKER_FILTER_REF: "docker.elastic.co/beats-dev"
  BUILDX: "0"

steps:
  - label: ":linux: multiarch Linux x86_64/arm64 FPM docker image"
    key: "build-and-publish-ubuntu-x86"
    if: build.env("BUILDKITE_PULL_REQUEST") != "false" || build.source == "ui" || build.branch == "main" || build.branch =~ /^[0-9]+\.[0-9]+$$/
    plugins:
      - monorepo-diff#v1.2.0:
          diff: "git diff --name-only HEAD~1"
          interpolation: false
          watch:
            - path:
                - .buildkite/fpm-pipeline.yml
                - .buildkite/scripts/llvm-fpm
              config:
                command: ".buildkite/scripts/llvm-fpm/build_and_publish.sh fpm ${DOCKER_FILTER_REF}"
                agents:
                  provider: "gcp"
                  image: "${IMAGE_UBUNTU_X86_64}"
                env:
                  - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                  - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                  - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}
                  - REPOSITORY="${STAGING_IMAGE}"
          notify:
            - github_commit_status:
                context: "Build FPM / Ubuntu X86_64"
