# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_GVM_VERSION: "v0.5.1"
  IMAGE_UBUNTU_X86_64: "family/core-ubuntu-2204"
  DOCKER_REGISTRY: "docker.elastic.co"
  STAGING_IMAGE: "${DOCKER_REGISTRY}/observability-ci"
  MAKEFILE: "fpm"
  CHANGESET_FILE: ".buildkite/scripts/changeset/fpm"
  DOCKER_FILTER_REF: "docker.elastic.co/beats-dev"
  BUILDX: "0"

steps:
  - label: ":linux: multiarch Linux x86_64/arm64 FPM docker image"
    key: "build-and-publish-ubuntu-x86"
    if: build.env("BUILDKITE_PULL_REQUEST") != "false" || build.source == "ui" || build.branch == "main" || build.branch =~ /^[0-9]+\.[0-9]+$$/
    command:
      - ".buildkite/scripts/llvm-fpm/build_and_publish.sh ${MAKEFILE} ${CHANGESET_FILE} ${DOCKER_FILTER_REF}"
    notify:
      - github_commit_status:
          context: "Build FPM / Ubuntu X86_64"
    env:
      REPOSITORY: "${STAGING_IMAGE}"
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
    plugins:
      # See https://github.com/elastic/oblt-infra/blob/main/conf/resources/repos/golang-crossbuild/01-gcp-buildkite-oidc.tf
      # This plugin authenticates to Google Cloud using the OIDC token.
      - elastic/oblt-google-auth#v1.3.0:
          lifetime: 10800 # seconds
          project-id: "elastic-observability-ci"
          project-number: "911195782929"
