# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_GVM_VERSION: "v0.5.1"
  IMAGE_UBUNTU_X86_64: "family/core-ubuntu-2204"
  IMAGE_UBUNTU_ARM_64: "core-ubuntu-2004-aarch64"
  GCP_DEFAULT_X86_64_MACHINE_TYPE: "n2-standard-16"
  DOCKER_REGISTRY: "docker.elastic.co"
  STAGING_IMAGE: "${DOCKER_REGISTRY}/observability-ci"
  MAKEFILE: "go/llvm-apple"
  CHANGESET_FILE: ".buildkite/scripts/changeset/llvm-apple"
  DOCKER_FILTER_REF: "*/*/golang-crossbuild:llvm-apple*"
  BUILDX: "0"
steps:
  - label: ":linux: Build LLVM Apple / Ubuntu X86_64 - {{matrix.debianVersion}}"
    key: "build-ubuntu-x86"
    if: build.env("BUILDKITE_PULL_REQUEST") != "false" || build.source == "ui" || build.branch == "main" || build.branch =~ /^[0-9]+\.[0-9]+$$/
    command:
      - ".buildkite/scripts/llvm-fpm/build.sh ${MAKEFILE} ${CHANGESET_FILE} ${DOCKER_FILTER_REF}"
      - ".buildkite/scripts/llvm-fpm/publish.sh ${MAKEFILE} ${CHANGESET_FILE}"
    notify:
      - github_commit_status:
          context: "Build LLVM Apple / Ubuntu X86_64"
    env:
      TAG_EXTENSION: "-debian{{matrix.debianVersion}}-amd64"
      REPOSITORY: "${STAGING_IMAGE}"
      DEBIAN_VERSION: "{{matrix.debianVersion}}"
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
      machineType: "${GCP_DEFAULT_X86_64_MACHINE_TYPE}"
    retry:
      automatic:
        - limit: 1
    matrix:
      setup:
        debianVersion:
          - "10"
          - "11"
          - "12"

  - label: ":linux: Build LLVM Apple / Ubuntu ARM - {{matrix.debianVersion}}"
    key: "build-ubuntu-arm"
    if: build.env("BUILDKITE_PULL_REQUEST") != "false" || build.source == "ui" || build.branch == "main" || build.branch =~ /^[0-9]+\.[0-9]+$$/
    command:
      - ".buildkite/scripts/llvm-fpm/build.sh ${MAKEFILE} ${CHANGESET_FILE} ${DOCKER_FILTER_REF}"
      - ".buildkite/scripts/llvm-fpm/publish.sh ${MAKEFILE} ${CHANGESET_FILE}"
    notify:
      - github_commit_status:
          context: "Build LLVM Apple / Ubuntu ARM"
    env:
      TAG_EXTENSION: "-debian{{matrix.debianVersion}}-arm64"
      REPOSITORY: "${STAGING_IMAGE}"
      DEBIAN_VERSION: "{{matrix.debianVersion}}"
    agents:
      provider: "aws"
      imagePrefix: "${IMAGE_UBUNTU_ARM_64}"
      instanceType: "t4g.large"
    matrix:
      setup:
        debianVersion:
          - "10"
          - "11"
          - "12"
