ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN dpkg --add-architecture armel \
    && apt update -y --no-install-recommends \
    && apt upgrade -y --no-install-recommends \
    && apt full-upgrade -y --no-install-recommends \
    && apt install -qq -y --no-install-recommends \
        crossbuild-essential-armel \
        linux-libc-dev-armel-cross

RUN apt install -qq -y \
        libc-dev:armel \
        libpopt-dev:armel \
        linux-libc-dev:armel

{{- if eq .DEBIAN_VERSION "9"}}
# librpm-dev
RUN apt install -y \
        librpm-dev:armel \
        librpm3:armel \
        librpmio3:armel \
        librpmbuild3:armel \
        librpmsign3:armel \
        libxml2-dev:armel \
        libsqlite3-dev:armel \
        libnss3:armel \
        libsqlite3-0:armel \
        libxml2:armel \
        libsqlite3-0:armel

# libsystemd-dev
RUN apt install -y \
        libsystemd-dev:armel libsystemd0:armel liblz4-1:armel
{{- end }}

{{- if or (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11")}}
# librpm-dev
RUN apt install -y \
        librpm-dev:armel

# libsystemd-dev
RUN apt install -y \
        libsystemd-dev:armel
{{- end }}

RUN rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && arm-linux-gnueabi-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && file helloWorld | cut -d "," -f 3 | grep -c 'EABI'\
  && rm helloWorld.c helloWorld

RUN cd /libpcap/libpcap-1.8.1 \
	&& CC=arm-linux-gnueabi-gcc ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no --host=arm-linux-gnueabi --with-pcap=linux \
	&& make

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
