---
name: common build tasks
inputs:
  branch:
    description: 'What branch'
    required: true
  go-minor:
    description: 'What Go minor version ([0-9]+.[0.9]+)'
    required: true
  command:
    description: 'What updatecli command'
    default: 'apply'
    required: false
  slack-message:
    description: 'Slack message if failure'
    required: false
    default: ":traffic_cone: updatecli failed for `${{ github.repository }}@${{ github.ref_name }}`, @agent-team please look what's going on <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>"
  slack-channel-id:
    description: 'Slack channel ID'
    required: false
    default: "#ingest-notifications"
  slack-bot-token:
    description: 'Specify the slack bot token.'
    required: true
  github-token:
    description: "The GitHub access token."
    required: true
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@92a13b95c2cd9f1c6742c965509203c6a5635ed7 # v2.68.0

      - name: Run Updatecli in Apply mode
        run: updatecli ${{ env.COMMAND }} --config ./.github/updatecli.d/bump-golang.yml
        env:
          COMMAND: ${{ inputs.command }}
          BRANCH: ${{ inputs.branch }}
          GO_MINOR: ${{ inputs.go-minor }}
          GITHUB_TOKEN: ${{ inputs.github-token }}
        shell: bash

      - if: ${{ failure()  }}
        uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # v1.27.0
        with:
          channel-id: ${{ inputs.slack-channel-id }}
          payload: |
            {
              "text": "${{ env.SLACK_MESSAGE }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.SLACK_MESSAGE }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
          SLACK_MESSAGE: ${{ inputs.slack-message }}
