---
name: common build tasks
inputs:
  branch:
    description: 'What branch'
    required: true
  go-minor:
    description: 'What Go minor version ([0-9]+.[0.9]+)'
    required: true
  messageIfFailure:
    description: 'Vault secret ID'
    required: false
    default: ":traffic_cone: updatecli failed for `${{ github.repository }}@${{ github.ref_name }}`, @agent-team please look what's going on <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>"
  notifySlackChannel:
    description: 'Vault secret ID'
    required: false
    default: "#ingest-notifications"
  vaultUrl:
    description: 'Vault URL'
    required: true
  vaultRoleId:
    description: 'Vault role ID'
    required: true
  vaultSecretId:
    description: 'Vault secret ID'
    required: true
  command:
    description: 'What updatecli command'
    default: 'apply'
    required: false

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - uses: elastic/apm-pipeline-library/.github/actions/updatecli@current
        with:
          vaultUrl: ${{ inputs.vaultUrl }}
          vaultRoleId: ${{ inputs.vaultRoleId }}
          vaultSecretId: ${{ inputs.vaultSecretId }}
          command: ${{ inputs.command }}
          pipeline: ./.github/updatecli.d/bump-golang.yml
          notifySlackChannel: ${{ inputs.notifySlackChannel }}
          messageIfFailure: ${{ inputs.messageIfFailure }}
        env:
          BRANCH: ${{ inputs.branch }}
          GO_MINOR: ${{ inputs.go-minor }}
