ARG REPOSITORY
ARG VERSION
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base

RUN \
    dpkg --add-architecture mipsel \
    && apt-get update -qq \
    && apt-get install -qq -y \
      --no-install-recommends \
      --allow-unauthenticated \
        crossbuild-essential-mipsel \
        gcc-mipsel-linux-gnu \
        g++-mipsel-linux-gnu \
        librpm-dev:mipsel \
        libc-dev:mipsel \
        libpopt-dev:mipsel \
        linux-libc-dev:mipsel \
        libxml2-dev:mipsel \
        libxml2:mipsel \
        libicu-dev:mipsel \
        libicu57:mipsel \
        icu-devtools:mipsel \
        libsystemd-dev:mipsel \
    && rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && mipsel-linux-gnu-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'MIPS R3000' \
  && readelf -h helloWorld | grep -c 'ELF32' \
  && readelf -h helloWorld | grep -c "little endian" \
  && rm helloWorld.c helloWorld

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
