ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN dpkg --add-architecture armel \
    && apt-get update -qq \
    && apt-get install -y \
      --no-install-recommends \
      --allow-unauthenticated \
        crossbuild-essential-armel \
        linux-libc-dev-armel-cross

RUN apt-get install -y \
      --no-install-recommends \
      --allow-unauthenticated \
        libc-dev:armel \
        libpopt-dev:armel \
        linux-libc-dev:armel

# librpm-dev
RUN apt-get install -y \
      --no-install-recommends \
      --allow-unauthenticated \
        librpm-dev:armel \
        librpm3:armel \
        librpmio3:armel \
        librpmbuild3:armel \
        librpmsign3:armel \
        libxml2-dev:armel \
        libsqlite3-dev:armel \
        libnss3:armel \
        libsqlite3-0:armel \
        libxml2:armel \
        libsqlite3-0:armel

# libsystemd-dev
RUN apt-get install -y  \
      --no-install-recommends \
      --allow-unauthenticated \
        libsystemd-dev:armel libsystemd0:armel liblz4-1:armel \
    && rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && arm-linux-gnueabi-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && file helloWorld | cut -d "," -f 3 | grep -c 'EABI'\
  && rm helloWorld.c helloWorld

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
