ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN dpkg --add-architecture mips64el \
    && apt update -y --no-install-recommends \
    && apt upgrade -y --no-install-recommends \
    && apt full-upgrade -y --no-install-recommends \
    && apt install -qq -y --no-install-recommends \
        crossbuild-essential-mipsel \
        gcc-mips64el-linux-gnuabi64 \
        g++-mips64el-linux-gnuabi64 \
        gcc-mips64-linux-gnuabi64 \
        g++-mips64-linux-gnuabi64 \
        linux-libc-dev-mips64el-cross

RUN apt install -qq -y \
        libc-dev:mips64el \
        libpopt-dev:mips64el \
        linux-libc-dev:mips64el

{{- if eq .DEBIAN_VERSION "9" }}
# librpm-dev
RUN apt install -y \
        libelf1:mips64el \
        libicu-dev:mips64el \
        libicu57:mips64el \
        librpm-dev:mips64el \
        librpm3:mips64el \
        librpmio3:mips64el \
        librpmbuild3:mips64el \
        librpmsign3:mips64el \
        libxml2-dev:mips64el \
        libsqlite3-dev:mips64el \
        libnss3:mips64el \
        libsqlite3-0:mips64el \
        libxml2:mips64el \
        libsqlite3-0:mips64el

# libsystemd-dev
# RUN apt install -y \
#         libsystemd-dev:mips64el libsystemd0:mips64el liblz4-1:mips64el
{{- end }}

{{- if or (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11")}}
# librpm-dev
RUN apt install -y \
        librpm-dev:mips64el

# libsystemd-dev
RUN apt install -y \
        libsystemd-dev:mips64el
{{- end }}

RUN rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && mips64el-linux-gnuabi64-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'MIPS R3000' \
  && readelf -h helloWorld | grep -c 'ELF64' \
  && readelf -h helloWorld | grep -c "little endian" \
  && rm helloWorld

# Basic test
RUN cd / \
  && mips64-linux-gnuabi64-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'MIPS R3000' \
  && readelf -h helloWorld | grep -c 'ELF64' \
  && readelf -h helloWorld | grep -c "big endian" \
  && rm helloWorld.c helloWorld

RUN cd /libpcap/libpcap-1.8.1 \
  && cp -R /libpcap/libpcap-1.8.1 /libpcap/libpcap-1.8.1-mips64 \
  && cp -R /libpcap/libpcap-1.8.1 /libpcap/libpcap-1.8.1-mips64el \
  && cd /libpcap/libpcap-1.8.1-mips64 \
	&& CC=mips64-linux-gnuabi64-gcc ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no --host=mips64-unknown-linux-gnu --with-pcap=linux \
	&& make \
  && cd /libpcap/libpcap-1.8.1-mips64el \
	&& CC=mips64el-linux-gnuabi64-gcc ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no --host=mips64el-unknown-linux-gnu --with-pcap=linux \
	&& make

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
