ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN dpkg --add-architecture mips \
    && apt update -y --no-install-recommends \
    && apt upgrade -y --no-install-recommends \
    && apt full-upgrade -y --no-install-recommends \
    && apt install -qq -y --no-install-recommends \
        crossbuild-essential-mipsel \
        gcc-mips-linux-gnu \
        g++-mips-linux-gnu \
        linux-libc-dev-mips-cross

RUN apt install -qq -y \
        libc-dev:mips \
        libpopt-dev:mips \
        linux-libc-dev:mips

{{- if eq .DEBIAN_VERSION "9" }}
# librpm-dev
RUN apt install -y \
        libelf1:mips \
        libicu-dev:mips \
        libicu57:mips \
        librpm-dev:mips \
        librpm3:mips \
        librpmio3:mips \
        librpmbuild3:mips \
        librpmsign3:mips \
        libxml2-dev:mips \
        libsqlite3-dev:mips \
        libnss3:mips \
        libsqlite3-0:mips \
        libxml2:mips \
        libsqlite3-0:mips

# libsystemd-dev
# RUN apt install -y \
#         libsystemd-dev:mips libsystemd0:mips liblz4-1:mips
{{- end }}

{{- if or (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11")}}
# librpm-dev
RUN apt install -y \
        librpm-dev:mips

# libsystemd-dev
RUN apt install -y \
        libsystemd-dev:mips
{{- end }}

RUN rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && mips-linux-gnu-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'MIPS R3000' \
  && readelf -h helloWorld | grep -c 'ELF32' \
  && readelf -h helloWorld | grep -c "big endian" \
  && rm helloWorld

# Basic test
RUN cd / \
  && mipsel-linux-gnu-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'MIPS R3000' \
  && readelf -h helloWorld | grep -c 'ELF32' \
  && readelf -h helloWorld | grep -c "little endian" \
  && rm helloWorld.c helloWorld

RUN cd /libpcap/libpcap-1.8.1 \
  && cp -R /libpcap/libpcap-1.8.1 /libpcap/libpcap-1.8.1-mips \
  && cp -R /libpcap/libpcap-1.8.1 /libpcap/libpcap-1.8.1-mipsel \
  && cd /libpcap/libpcap-1.8.1-mips \
	&& CC=mips-linux-gnu-gcc ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no --host=mips-unknown-linux-gnu --with-pcap=linux \
	&& make \
  && cd /libpcap/libpcap-1.8.1-mipsel \
	&& CC=mipsel-linux-gnu-gcc ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no --host=mipsel-unknown-linux-gnu --with-pcap=linux \
	&& make

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
