ARG REPOSITORY
ARG VERSION
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base

RUN \
    dpkg --add-architecture ppc64el \
    && apt-get update -qq \
    && apt-get install -y -qq \
      --no-install-recommends \
      --allow-unauthenticated \
        g++-powerpc64le-linux-gnu \
        gcc-powerpc64le-linux-gnu \
        crossbuild-essential-ppc64el \
        librpm-dev:ppc64el \
        libc-dev:ppc64el \
        libpopt-dev:ppc64el \
        linux-libc-dev:ppc64el \
        libxml2-dev:ppc64el \
        libxml2:ppc64el \
        libicu-dev:ppc64el \
        libicu57:ppc64el \
        icu-devtools:ppc64el \
        libsystemd-dev:ppc64el \
    && rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && powerpc64le-linux-gnu-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'PowerPC64' \
  && readelf -h helloWorld | grep -c 'ELF64' \
  && readelf -h helloWorld | grep -c "little endian" \
  && rm helloWorld.c helloWorld

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
