ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN apt-get update
RUN \
    dpkg --add-architecture mips64el \
    && apt-get -o Acquire::Check-Valid-Until=false update -qq \
    && apt-get install -y \
      --no-install-recommends \
      --allow-unauthenticated \
        crossbuild-essential-mipsel \
        gcc-6-mips64el-linux-gnuabi64 \
        g++-6-mips64el-linux-gnuabi64 \
        gcc-6-mips64-linux-gnuabi64 \
        g++-6-mips64-linux-gnuabi64

RUN apt-get install -y \
      --no-install-recommends \
      --allow-unauthenticated \
        libc-dev:mips64el \
        libpopt-dev:mips64el \
        linux-libc-dev:mips64el

# librpm-dev
RUN apt-get install -y \
      --no-install-recommends \
      --allow-unauthenticated \
        librpm-dev:mips64el \
        librpm3:mips64el \
        librpmio3:mips64el \
        librpmbuild3:mips64el \
        librpmsign3:mips64el \
        libxml2-dev:mips64el \
        libsqlite3-dev:mips64el \
        libnss3:mips64el \
        libsqlite3-0:mips64el \
        libxml2:mips64el \
        libsqlite3-0:mips64el

# libsystemd-dev
RUN apt-get install -y  \
      --no-install-recommends \
      --allow-unauthenticated \
        libsystemd-dev:mips64el libsystemd0:mips64el liblz4-1:mips64el \
    && rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && mips64el-linux-gnuabi64-gcc-6 helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'MIPS R3000' \
  && readelf -h helloWorld | grep -c 'ELF64' \
  && readelf -h helloWorld | grep -c "little endian" \
  && rm helloWorld

# Basic test
RUN cd / \
  && mips64-linux-gnuabi64-gcc-6 helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'MIPS R3000' \
  && readelf -h helloWorld | grep -c 'ELF64' \
  && readelf -h helloWorld | grep -c "big endian" \
  && rm helloWorld.c helloWorld

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
