ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN dpkg --add-architecture ppc64el \
    && apt update -y --no-install-recommends \
    && apt upgrade -y --no-install-recommends \
    && apt full-upgrade -y --no-install-recommends \
    && apt install -qq -y --no-install-recommends \
        g++-powerpc64-linux-gnu \
        gcc-powerpc64-linux-gnu \
        crossbuild-essential-ppc64el

RUN apt install -qq -y \
        libc-dev:ppc64el \
        libpopt-dev:ppc64el \
        linux-libc-dev:ppc64el

{{- if eq .DEBIAN_VERSION "9" }}
RUN apt install -qq -y \
        libelf1:ppc64el \
        libicu-dev:ppc64el \
        libicu57:ppc64el \
        librpm-dev:ppc64el \
        libxml2-dev:ppc64el \
        libxml2:ppc64el \
        librpm3:ppc64el \
        librpmio3:ppc64el \
        librpmbuild3:ppc64el \
        librpmsign3:ppc64el \
        libsqlite3-dev:ppc64el \
        libnss3:ppc64el \
        libsqlite3-0:ppc64el

# RUN apt install -y \
#         libsystemd-dev:ppc64el libsystemd0:ppc64el liblz4-1:ppc64el
{{- end }}

{{- if or (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11")}}
# librpm-dev
RUN apt install -y \
        librpm-dev:ppc64el

# libsystemd-dev
RUN apt install -y \
        libsystemd-dev:ppc64el
{{- end }}

RUN rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && powerpc64le-linux-gnu-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'PowerPC64' \
  && readelf -h helloWorld | grep -c 'ELF64' \
  && readelf -h helloWorld | grep -c "little endian" \
  && rm helloWorld.c helloWorld

RUN cd /libpcap/libpcap-1.8.1 \
  && cp -R /libpcap/libpcap-1.8.1 /libpcap/libpcap-1.8.1-ppc64 \
  && cp -R /libpcap/libpcap-1.8.1 /libpcap/libpcap-1.8.1-ppc64el \
  && cd /libpcap/libpcap-1.8.1-ppc64 \
	&& CC=powerpc64-linux-gnu-gcc ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no --host=ppc64-unknown-linux-gnu --with-pcap=linux \
	&& make \
  && cd /libpcap/libpcap-1.8.1-ppc64el \
	&& CC=powerpc64le-linux-gnu-gcc ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no --host=ppc64el-unknown-linux-gnu --with-pcap=linux \
	&& make

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
