IMAGES         := base main darwin npcap
DEBIAN_VERSION := 8
TAG_EXTENSION  := -debian8

export DEBIAN_VERSION TAG_EXTENSION

build:
	export |grep TAG_EXTENSION
	@$(foreach var,$(IMAGES),$(MAKE) -C $(var) build || exit 1;)

# Requires login at https://docker.elastic.co:7000/.
push:
	@$(foreach var,$(IMAGES),$(MAKE) -C $(var) push || exit 1;)

.PHONY: build push
