IMAGES         := base main arm armhf armel mips ppc s390x npcap
DEBIAN_VERSION := 11
TAG_EXTENSION  := -debian11

export DEBIAN_VERSION TAG_EXTENSION

build:
	@$(foreach var,$(IMAGES),$(MAKE) -C $(var) build || exit 1;)

# Requires login at https://docker.elastic.co:7000/.
push:
	@$(foreach var,$(IMAGES),$(MAKE) -C $(var) push || exit 1;)

.PHONY: build push
