IMAGES         := base main
DEBIAN_VERSION := 7
TAG_EXTENSION  := -debian7

export DEBIAN_VERSION TAG_EXTENSION

build:
	@$(foreach var,$(IMAGES),$(MAKE) -C $(var) build || exit 1;)

# Requires login at https://docker.elastic.co:7000/.
push:
	@$(foreach var,$(IMAGES),$(MAKE) -C $(var) push || exit 1;)

.PHONY: build push
