SELF_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
include $(SELF_DIR)/../Makefile.common

NAME           := golang-crossbuild
VERSION        := $(shell cat $(SELF_DIR)/../.go-version)
DEBIAN_VERSION ?= 9
SUFFIX         := -$(shell basename $(CURDIR))
TAG_EXTENSION  ?=
FIPS           ?=
ifeq "${FIPS}" "true"
ifeq ($(findstring -fips,$(TAG_EXTENSION)),)
TAG_EXTENSION:=$(TAG_EXTENSION)-fips
endif
endif

export DEBIAN_VERSION TAG_EXTENSION NPCAP_FILE VERSION

DOCKER_CMD := docker build --progress=plain

build: copy-npcap copy-sdks
	@echo ">> Building $(REPOSITORY)/$(NAME):$(VERSION)$(SUFFIX)$(TAG_EXTENSION)"
	@go run $(SELF_DIR)/../template.go -t Dockerfile.tmpl -o Dockerfile
	@$(DOCKER_CMD) -t "$(REPOSITORY)/$(NAME):$(VERSION)$(SUFFIX)$(TAG_EXTENSION)" \
	--build-arg REPOSITORY=$(REPOSITORY) \
	--build-arg VERSION=$(VERSION) \
	--build-arg DEBIAN_VERSION=$(DEBIAN_VERSION) \
	--build-arg TAG_EXTENSION=$(TAG_EXTENSION) \
	--build-arg IMAGE="$(REPOSITORY)/$(NAME):$(VERSION)$(SUFFIX)$(TAG_EXTENSION)" \
	--build-arg VCS_REF="$(VCS_REF)" \
	--build-arg VCS_URL="$(VCS_URL)" \
	--build-arg BUILD_DATE="$(BUILD_DATE)" \
	.
	@echo ">> Validating $(REPOSITORY)/$(NAME):$(VERSION)$(SUFFIX)$(TAG_EXTENSION)"
	docker run --rm --entrypoint /usr/local/go/bin/go "$(REPOSITORY)/$(NAME):$(VERSION)$(SUFFIX)$(TAG_EXTENSION)" version | grep "go$(VERSION)"

build-arm: copy-sdks
	@echo $(SELF_DIR)
	@echo ">> Building $(REPOSITORY)/$(NAME):$(VERSION)$(SUFFIX)$(TAG_EXTENSION)"
	@go run $(SELF_DIR)/../template.go -t Dockerfile.tmpl -o Dockerfile
	@docker build -t "$(REPOSITORY)/$(NAME):$(VERSION)$(SUFFIX)$(TAG_EXTENSION)" \
	--progress=plain \
	--build-arg REPOSITORY=$(REPOSITORY) \
	--build-arg VERSION=$(VERSION) \
	--build-arg DEBIAN_VERSION=$(DEBIAN_VERSION) \
	--build-arg TAG_EXTENSION=$(TAG_EXTENSION) \
	--build-arg IMAGE="$(REPOSITORY)/$(NAME):$(VERSION)$(SUFFIX)$(TAG_EXTENSION)" \
	--build-arg VCS_REF="$(VCS_REF)" \
	--build-arg VCS_URL="$(VCS_URL)" \
	--build-arg BUILD_DATE="$(BUILD_DATE)" \
	.
	@echo ">> Validating $(REPOSITORY)/$(NAME):$(VERSION)$(SUFFIX)$(TAG_EXTENSION)"
	docker run --rm --entrypoint /usr/local/go/bin/go "$(REPOSITORY)/$(NAME):$(VERSION)$(SUFFIX)$(TAG_EXTENSION)" version | grep "go$(VERSION)"

.PHONY: build build-arm
