#!/bin/bash

set -euo pipefail

source .buildkite/scripts/common.sh

if [[ "$BUILDKITE_PIPELINE_SLUG" == "golang-crossbuild" && "$BUILDKITE_STEP_KEY" == "release-post" ]]; then
    export GITHUB_USERNAME="elasticmachine"
    export GITHUB_EMAIL="elasticmachine@elastic.co"
    export GITHUB_TOKEN_SECRET=$VAULT_GITHUB_TOKEN
fi
