#!/bin/bash

set -euo pipefail

source .buildkite/scripts/common.sh

if [[ "$BUILDKITE_PIPELINE_SLUG" == "golang-crossbuild" && "$BUILDKITE_STEP_KEY" == "release-post" ]]; then
    GITHUB_USERNAME_SECRET="elasticmachine"
    export GITHUB_USERNAME_SECRET=$GITHUB_USERNAME_SECRET
    export GITHUB_EMAIL_SECRET="elasticmachine@elastic.co"
    export GITHUB_TOKEN_SECRET=$VAULT_GITHUB_TOKEN
fi
