ARG REPOSITORY
ARG VERSION
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base

RUN \
    dpkg --add-architecture armhf \
    && apt-get update -qq \
    && apt-get install -qq -y \
      --no-install-recommends \
      --allow-unauthenticated \
        crossbuild-essential-armhf \
        linux-libc-dev-armhf-cross \
        librpm-dev:armhf \
        libc-dev:armhf \
        libpopt-dev:armhf \
        linux-libc-dev:armhf \
        libxml2-dev:armhf \
        libxml2:armhf \
        libicu-dev:armhf \
        libicu57:armhf \
        icu-devtools:armhf \
        libsystemd-dev:armhf \
    && rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
