ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN apt-get update
RUN dpkg --add-architecture mips64el \
    && apt update -y --no-install-recommends \
    && apt upgrade -y --no-install-recommends \
    && apt full-upgrade -y --no-install-recommends \
    && apt install -qq -y --no-install-recommends \
      --no-install-recommends \
      --allow-unauthenticated \
        crossbuild-essential-mipsel \
        gcc-mips-linux-gnu \
        g++-mips-linux-gnu \
        gcc-6-mips64-linux-gnuabi64 \
        g++-6-mips64-linux-gnuabi64 \
        gcc-6-mips64el-linux-gnuabi64 \
        g++-6-mips64el-linux-gnuabi64

RUN apt install -qq -y \
        libc-dev:mips64el \
        libpopt-dev:mips64el \
        linux-libc-dev:mips64el

{{ if eq .DEBIAN_VERSION "9" }}
# librpm-dev
RUN apt install -y \
        librpm-dev:mips64el \
        librpm3:mips64el \
        librpmio3:mips64el \
        librpmbuild3:mips64el \
        librpmsign3:mips64el \
        libxml2-dev:mips64el \
        libsqlite3-dev:mips64el \
        libnss3:mips64el \
        libsqlite3-0:mips64el \
        libxml2:mips64el \
        libsqlite3-0:mips64el

# libsystemd-dev
# RUN apt install -y \
#         libsystemd-dev:mips64el libsystemd0:mips64el liblz4-1:mips64el
{{ end }}

{{if eq .DEBIAN_VERSION "10"}}
# librpm-dev
RUN apt install -y \
        librpm-dev:mips64el

# libsystemd-dev
RUN apt install -y \
        libsystemd-dev:mips64el
{{ end }}

RUN rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && mips64el-linux-gnuabi64-gcc-6 helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'MIPS R3000' \
  && readelf -h helloWorld | grep -c 'ELF64' \
  && readelf -h helloWorld | grep -c "little endian" \
  && rm helloWorld.c helloWorld

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
