ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN \
    dpkg --add-architecture i386 \
    && apt-get -o Acquire::Check-Valid-Until=false update \
    && apt-get install -qq -y --no-install-recommends --allow-unauthenticated \
        clang \
        g++ \
        gcc \
        gcc-multilib \
        libc6-dev \
        libc6-dev-i386 \
        linux-libc-dev:i386 \
        mingw-w64 \
        mingw-w64-tools \
        patch \
        xz-utils \
        unzip

{{- if ne .DEBIAN_VERSION "7" }}
# librpm-dev
RUN apt install -y --no-install-recommends --allow-unauthenticated\
        librpm-dev \
        libxml2-dev \
        libsqlite3-dev

# libsystemd-dev
RUN apt install -y --no-install-recommends --allow-unauthenticated\
         libsystemd-dev
{{- end }}

{{- if or (eq .DEBIAN_VERSION "9") (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11") }}
# msitools
RUN apt install -y --no-install-recommends --allow-unauthenticated\
         msitools
{{- end }}

RUN rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && file helloWorld | cut -d "," -f 2 | grep -c 'x86-64' \
  && rm helloWorld.c helloWorld

RUN cd /libpcap/libpcap-1.8.1 \
  && cp -R /libpcap/libpcap-1.8.1 /libpcap/libpcap-1.8.1-i386 \
  && cp -R /libpcap/libpcap-1.8.1 /libpcap/libpcap-1.8.1-amd64 \
  && cd /libpcap/libpcap-1.8.1-i386 \
	&& CFLAGS="-m32" LDFLAGS="-m32" ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no \
	&& make \
  && cd /libpcap/libpcap-1.8.1-amd64 \
  && ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no \
  && make

RUN curl -sSLO https://storage.googleapis.com/obs-ci-cache/beats/WpdPack_4_1_2.zip \
  && mkdir -p /libpcap/win \
  && echo "ea799cf2f26e4afb1892938070fd2b1ca37ce5cf75fec4349247df12b784edbd  WpdPack_4_1_2.zip" | sha256sum -c - \
  && unzip WpdPack_4_1_2.zip -d /libpcap/win \
  && rm WpdPack_4_1_2.zip \
  && cd /libpcap/win/WpdPack \
  && curl -sSLO https://raw.githubusercontent.com/elastic/beats/master/packetbeat/lib/windows-64/wpcap.dll \
  && echo "0948518b229fb502b9c063966fc3afafbb749241a1c184f6eb7d532e00bce1d8  wpcap.dll" | sha256sum -c - \
  && gendef wpcap.dll \
  && x86_64-w64-mingw32-dlltool \
    --as-flags=--64 \
    -m i386:x86-64 \
    -k \
    --output-lib /libpcap/win/WpdPack/Lib/x64/libwpcap.a \
    --input-def /libpcap/win/WpdPack/wpcap.def

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
