ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
{{- if or (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11")}}
FROM --platform=linux/amd64  docker.elastic.co/beats-dev/golang-crossbuild:llvm-apple-debian{{ .DEBIAN_VERSION }}-amd64 AS build-llvm-apple-amd64
FROM --platform=linux/arm64  docker.elastic.co/beats-dev/golang-crossbuild:llvm-apple-debian{{ .DEBIAN_VERSION }}-arm64 AS build-llvm-apple-arm64
# workaround to https://github.com/moby/moby/issues/34482
ARG TARGETARCH=amd64
ARG BUILDARCH=amd64
FROM build-llvm-apple-${TARGETARCH} as build-llvm-apple
ARG TARGETARCH
ARG BUILDARCH
RUN echo "Building ${TARGETARCH} on a ${BUILDARCH}"
{{- end }}
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

{{- if and (ne .DEBIAN_VERSION "10") (ne .DEBIAN_VERSION "11")}}
RUN echo "This Docker image will work only with Debian >10" && exit 1
{{- end }}

RUN \
    apt-get -o Acquire::Check-Valid-Until=false update \
    && apt-get install -qq -y --no-install-recommends --allow-unauthenticated \
        cmake \
        patch \
        libssl-dev \
        libxml2-dev \
        lzma-dev \
        uuid-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build-llvm-apple /llvm-apple-Linux.tar.gz /tmp/llvm-apple-Linux.tar.gz
RUN tar -xzf /tmp/llvm-apple-Linux.tar.gz --strip 1 -C /usr/local \
  && rm /tmp/llvm-apple-Linux.tar.gz

ARG OSXCROSS_PATH=/usr/local/osxcross
COPY --from=build-llvm-apple /osxcross.tar.gz /tmp/osxcross.tar.gz
RUN tar -xzf /tmp/osxcross.tar.gz -C / \
  && rm /tmp/osxcross.tar.gz

ENV PATH $PATH:$OSXCROSS_PATH/bin
# Add osxcross libraries to the library PATH
ENV LD_LIBRARY_PATH $OSXCROSS_PATH/lib:/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH

COPY rootfs /

# Basic test
RUN cd / \
  && o64-clang helloWorld.c -o helloWorld.x86_64 \
  && file helloWorld.x86_64 \
  && file helloWorld.x86_64 | grep -c 'Mach-O 64-bit x86_64'

RUN cd / \
  && oa64-clang helloWorld.c -o helloWorld.arm64 \
  && file helloWorld.arm64 \
  && file helloWorld.arm64 | grep -c 'Mach-O 64-bit arm64'

RUN cd / \
  && oa64e-clang helloWorld.c -o helloWorld.arm64e \
  && file helloWorld.arm64e \
  && file helloWorld.arm64e | grep -c 'Mach-O 64-bit arm64'

RUN cd / \
  && lipo -create -output helloWorld.universal helloWorld.x86_64 helloWorld.arm64e \
  && file helloWorld.universal | grep 'Mach-O universal binary' \
  && rm helloWorld.*


# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
