ARG DEBIAN_VERSION
FROM arm64v8/debian:${DEBIAN_VERSION}

ARG DEBIAN_VERSION
# Replace sources.list in order to use archive.debian.org.
COPY sources-debian${DEBIAN_VERSION}.list /etc/apt/sources.list

RUN \
    apt-get -o Acquire::Check-Valid-Until=false update \
        && apt-get dist-upgrade -y \
        && apt-get install -qq -y --no-install-recommends --allow-unauthenticated \
            build-essential \
            ca-certificates \
            curl \
            git \
            gnupg \
            make \
            file \
            flex \
            bison \
            librpm-dev \
            libc-dev \
            libpopt-dev \
            linux-libc-dev \
            libxml2-dev \
            libxml2 \
            libicu-dev \
            libicu57 \
            icu-devtools \
            libsystemd-dev \
            librpm3  \
            librpmio3 \
            librpmbuild3 \
            librpmsign3 \
            libsqlite3-dev \
            libnss3 \
            libsqlite3-0 \
        && rm -rf /var/lib/apt/lists/*

ARG GOLANG_VERSION=1.23.0
ARG GOLANG_DOWNLOAD_URL=https://golang.org/dl/go$GOLANG_VERSION.linux-arm64.tar.gz
ARG GOLANG_DOWNLOAD_SHA256=62788056693009bcf7020eedc778cdd1781941c6145eab7688bd087bce0f8659

RUN curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
	&& echo "$GOLANG_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
	&& tar -C /usr/local -xzf golang.tar.gz \
	&& rm golang.tar.gz

ENV GOPATH /go
ENV PATH $PATH:/usr/local/go/bin

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

COPY rootfs /

# show the GLIBC version
RUN ldd --version

WORKDIR /

RUN mkdir -p /root/.config/go/telemetry && echo "off 2024-08-23" > /root/.config/go/telemetry/mode
RUN echo "#!/bin/bash\n" \
         "if [ \"$1\" = \"/usr/lib/go/pkg/tool/linux_amd64/compile\" ]; then echo \"compile version go1.23.0\" && exit 0; fi\n" \
         "\exec "$@\" || echo \"$@\"\n" > /root/toolexec.sh
RUN chmod +x /root/toolexec.sh
RUN go version \
    && go mod init github.com/elastic/golang-crossbuild-$GOLANG_VERSION-arm \
    && echo ">>> run go get -d" \
    && go get -d . \
    && echo ">>> run go build" \
    && go env \
    && echo "toolcompile=$(go tool compile -V)" \
    && go build -toolexec="/root/toolexec.sh" -o /crossbuild /entrypoint.go \
    && rm -rf /go/* /root/.cache/* /entrypoint.go

RUN curl -sSLO https://storage.googleapis.com/obs-ci-cache/beats/libpcap-1.8.1.tar.gz \
  && mkdir /libpcap \
	&& tar -xzf libpcap-1.8.1.tar.gz -C /libpcap \
  && cd /libpcap/libpcap-1.8.1 \
  && ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no --host=aarch64-unknown-linux-gnu --with-pcap=linux \
  && make

ENV GOLANG_CROSSBUILD=1
VOLUME      /app
WORKDIR     /app
ENTRYPOINT  ["/crossbuild"]
