ARG REPOSITORY
ARG VERSION
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base

RUN \
    dpkg --add-architecture armel \
    && apt-get update -qq \
    && apt-get install -qq -y \
      --no-install-recommends \
      --allow-unauthenticated \
        crossbuild-essential-armel \
        linux-libc-dev-armel-cross \
        librpm-dev:armel \
        libc-dev:armel \
        libpopt-dev:armel \
        linux-libc-dev:armel \
        libxml2-dev:armel \
        libxml2:armel \
        libicu-dev:armel \
        libicu57:armel \
        icu-devtools:armel \
        libsystemd-dev:armel \
    && rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && arm-linux-gnueabi-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'soft-float ABI' \
  && rm helloWorld.c helloWorld

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
