ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION} as BUILD_LLVM_APPLE

RUN \
    apt-get -o Acquire::Check-Valid-Until=false update \
    && apt-get install -qq -y --no-install-recommends --allow-unauthenticated \
        cmake \
        patch \
        libssl-dev \
        libxml2-dev \
        lzma-dev \
        uuid-dev \
    && rm -rf /var/lib/apt/lists/*

#https://www.llvm.org/docs/CMake.html
#https://github.com/apple/llvm-project
RUN mkdir -p /tmp/llvm-project && cd /tmp/llvm-project \
    && curl -sSL "https://github.com/apple/llvm-project/archive/refs/tags/swift-5.4.1-RELEASE.tar.gz" \
      | tar -C /tmp/llvm-project --strip=1 -xzf - \
    && mkdir build && cd build \
    && cmake -DLLVM_ENABLE_PROJECTS="clang" \
      -DCMAKE_BUILD_TYPE="Release" \
      -DLLVM_TARGETS_TO_BUILD="X86;AArch64" \
      -DLLVM_INCLUDE_TESTS=OFF \
      -DLLVM_INCLUDE_EXAMPLES=Off \
      -DLLVM_ENABLE_BACKTRACES=Off \
      -DLLVM_BUILD_32_BITS=OFF \
      /tmp/llvm-project/llvm \
    && cmake --build . \
    && cmake --build . --target package \
    && tar -xzf LLVM-*-Linux.tar.gz --strip 1 -C /usr/local

# Packaging the SDK on macOS https://github.com/tpoechtrager/osxcross#packaging-the-sdk
ARG OSXCROSS_SDK_URL=https://storage.googleapis.com/obs-ci-cache/beats/MacOSX11.3.sdk.tar.xz
ARG OSXCROSS_PATH=/usr/local/osxcross
ARG OSXCROSS_REV=035cc170338b7b252e3f13b0e3ccbf4411bffc41
ARG SDK_VERSION=11.3
ARG DARWIN_VERSION=20
ARG OSX_VERSION_MIN=10.9

RUN \
    mkdir -p /tmp/osxcross && cd /tmp/osxcross \
    && curl -sSL "https://codeload.github.com/tpoechtrager/osxcross/tar.gz/${OSXCROSS_REV}" \
        | tar -C /tmp/osxcross --strip=1 -xzf - \
    && curl -sSLo "tarballs/MacOSX${SDK_VERSION}.sdk.tar.xz" "${OSXCROSS_SDK_URL}" \
    && UNATTENDED=1 TARGET_DIR=${OSXCROSS_PATH} ./build.sh >/dev/null \
    && rm -rf "${OSXCROSS_PATH}/SDK/MacOSX*.sdk/usr/share/man" \
    && tar -czf osxcross.tar.gz ${OSXCROSS_PATH}

FROM debian:stable-slim

COPY --from=BUILD_LLVM_APPLE /tmp/llvm-project/build/LLVM-*-Linux.tar.gz /llvm-apple-Linux.tar.gz
COPY --from=BUILD_LLVM_APPLE /tmp/osxcross/osxcross.tar.gz /osxcross.tar.gz

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"

ENTRYPOINT /bin/bash
