ARG DEBIAN_VERSION
FROM debian:${DEBIAN_VERSION} as BUILD_LLVM_APPLE

ARG DEBIAN_VERSION
# Replace sources.list in order to use archive.debian.org.
COPY sources-debian${DEBIAN_VERSION}.list /etc/apt/sources.list

RUN apt-get -o Acquire::Check-Valid-Until=false update -y --no-install-recommends --allow-unauthenticated \
        && apt-get upgrade -y --no-install-recommends --allow-unauthenticated \
        && apt-get dist-upgrade -y --no-install-recommends --allow-unauthenticated \
        && apt-get install -y --no-install-recommends --allow-unauthenticated \
            build-essential \
            ca-certificates \
            curl \
            git \
            gnupg \
            make \
            file \
            flex \
            bison \
            cmake \
            patch \
            libssl-dev \
            libxml2-dev \
            lzma-dev \
            uuid-dev \
{{- if or (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11") (eq .DEBIAN_VERSION "12")}}
            binutils-multiarch \
            binutils-multiarch-dev \
            python3-venv \
            python3-pip \
            python3 \
{{- end }}
        && rm -rf /var/lib/apt/lists/*

#https://www.llvm.org/docs/CMake.html
#https://github.com/apple/llvm-project
RUN mkdir -p /tmp/llvm-project && cd /tmp/llvm-project \
    && curl -sSL "https://github.com/apple/llvm-project/archive/refs/tags/swift-5.6.3-RELEASE.tar.gz" \
      | tar -C /tmp/llvm-project --strip=1 -xzf - \
    && mkdir build && cd build \
    && cmake -DLLVM_ENABLE_PROJECTS="clang" \
      -DCMAKE_BUILD_TYPE="Release" \
      -DLLVM_TARGETS_TO_BUILD="X86;AArch64" \
      -DLLVM_INCLUDE_TESTS=OFF \
      -DLLVM_INCLUDE_EXAMPLES=Off \
      -DLLVM_ENABLE_BACKTRACES=Off \
      -DLLVM_BUILD_32_BITS=OFF \
      /tmp/llvm-project/llvm \
    && cmake --build . \
    && cmake --build . --target package \
    && tar -xzf LLVM-*-Linux.tar.gz --strip 1 -C /usr/local

# TODO think about replace this with the Docker image already created at https://github.com/crazy-max/docker-osxcross
ARG OSX_SDK="MacOSX12.3.sdk"
# Packaging the SDK on macOS https://github.com/tpoechtrager/osxcross#packaging-the-sdk
# alternative SDK already generated
ARG OSXCROSS_PATH=/usr/local/osxcross
ARG OSXCROSS_REV=f873f534c6cdb0776e457af8c7513da1e02abe59
ARG OSX_VERSION_MIN=10.10

RUN mkdir -p /tmp/osxcross
# https://raw.githubusercontent.com/crazy-max/docker-osxcross/main/patches/lcxx.patch
COPY lcxx.patch /tmp/osxcross/lcxx.patch

COPY sdks/${OSX_SDK}.tar.xz /tmp/osxcross/tarballs/${OSX_SDK}.tar.xz
RUN \
    cd /tmp/osxcross \
    && curl -sSL "https://codeload.github.com/tpoechtrager/osxcross/tar.gz/${OSXCROSS_REV}" \
        | tar -C /tmp/osxcross --strip=1 -xzf - \
    && patch -p1 < lcxx.patch \
    && UNATTENDED=1 ENABLE_COMPILER_RT_INSTALL=1 OSX_VERSION_MIN=${OSX_VERSION_MIN} TARGET_DIR=${OSXCROSS_PATH} ./build.sh >/dev/null \
    && rm -rf "/usr/osxcross/SDK/${OSX_SDK}/usr/share/man" \
    && tar -czf osxcross.tar.gz ${OSXCROSS_PATH}

FROM debian:stable-slim

COPY --from=BUILD_LLVM_APPLE /tmp/llvm-project/build/LLVM-*-Linux.tar.gz /llvm-apple-Linux.tar.gz
COPY --from=BUILD_LLVM_APPLE /tmp/osxcross/osxcross.tar.gz /osxcross.tar.gz

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"

ENTRYPOINT /bin/bash
