ARG REPOSITORY
ARG VERSION
ARG TAG_EXTENSION=''
FROM ${REPOSITORY}/golang-crossbuild:${VERSION}-base${TAG_EXTENSION}

RUN dpkg --add-architecture s390x \
    && apt update -y --no-install-recommends \
    && apt upgrade -y --no-install-recommends \
    && apt full-upgrade -y --no-install-recommends \
    && apt install -qq -y --no-install-recommends \
        g++-s390x-linux-gnu \
        gcc-s390x-linux-gnu

RUN apt install -qq -y \
        libc-dev:s390x \
        libpopt-dev:s390x \
        linux-libc-dev:s390x

{{- if eq .DEBIAN_VERSION "9" }}
RUN apt install -qq -y \
        libelf1:s390x \
        libicu-dev:s390x \
        libicu57:s390x \
        librpm-dev:s390x \
        libxml2-dev:s390x \
        libxml2:s390x \
        librpm3:s390x \
        librpmio3:s390x \
        librpmbuild3:s390x \
        librpmsign3:s390x \
        libsqlite3-dev:s390x \
        libnss3:s390x \
        libsqlite3-0:s390x

# RUN apt install -y \
#         libsystemd-dev:s390x libsystemd0:s390x liblz4-1:s390x
{{- end }}

{{- if or (eq .DEBIAN_VERSION "10") (eq .DEBIAN_VERSION "11")}}
# librpm-dev
RUN apt install -y \
        librpm-dev:s390x

# libsystemd-dev
RUN apt install -y \
        libsystemd-dev:s390x
{{- end }}

RUN rm -rf /var/lib/apt/lists/*

COPY rootfs /

# Basic test
RUN cd / \
  && s390x-linux-gnu-gcc helloWorld.c -o helloWorld \
  && file helloWorld \
  && readelf -h helloWorld \
  && readelf -h helloWorld | grep -c 'IBM S/390' \
  && readelf -h helloWorld | grep -c 'ELF64' \
  && readelf -h helloWorld | grep -c "big endian" \
  && rm helloWorld.c helloWorld

RUN cd /libpcap/libpcap-1.8.1 \
	&& CC=s390x-linux-gnu-gcc ./configure --enable-usb=no --enable-bluetooth=no --enable-dbus=no --host=s390x-ibm-linux-gnu --with-pcap=linux \
	&& make

# Build-time metadata as defined at http://label-schema.org.
ARG BUILD_DATE
ARG IMAGE
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
