---
name: bump-golang-previous

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1-6'

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/bump-golang
        with:
          # NOTE: when a new golang version please update me with 1.<go-version-1>
          branch: '1.24'
          # NOTE: when a new golang version please update me with 1.<go-version-1>
          go-minor: '1.24'
          command: '--experimental apply'
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
