---
name: bump-golang-previous

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 6'

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/bump-golang
        with:
          # NOTE: when a new golang version please update me with 1.<go-version-1>
          branch: '1.20'
          # NOTE: when a new golang version please update me with 1.<go-version-1>
          go-minor: '1.20'
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
