---
name: bump-golang-1.20

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 6'

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/bump-golang
        with:
          branch: '1.20'
          go-minor: '1.20'
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
