---
name: bump-golang-previous

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1-6'

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bump-golang
        with:
          # NOTE: when a new golang version please update me with 1.<go-version-1>
          branch: '1.20'
          # NOTE: when a new golang version please update me with 1.<go-version-1>
<<<<<<< HEAD
          go-minor: '1.20'
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
=======
          go-minor: '1.21'
>>>>>>> 8d5547d (github-actions: use github secrets for updatecli (#411))
          command: '--experimental apply'
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
