---
name: ci-fpm

on:
  push:
    paths:
      - 'fpm/**'
      - '.github/workflows/ci-fpm.yml'
      - '.github/actions/build-push/**'

permissions:
  contents: read

jobs:
  build-push:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4

      - name: Docker build and push
        uses: ./.github/actions/build-push
        with:
          docker-registry: ${{ secrets.ELASTIC_DOCKER_REGISTRY }}
          docker-username: ${{ secrets.ELASTIC_DOCKER_USERNAME }}
          docker-password: ${{ secrets.ELASTIC_DOCKER_PASSWORD }}
          make-directory: 'fpm'
          make-file: 'Makefile'
