---
name: ci-llvm-apple

on:
  push:
    paths:
      - 'go/llvm-apple/**'
      - '.github/workflows/ci-llvm-apple.yml'

permissions:
  contents: read

env:
  # NOTE: For some reason the repository is not production but staging.
  REPOSITORY: 'docker.elastic.co/observability-ci' 
  MAKE_DIR: 'go/llvm-apple'

jobs:
  build-push:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-24.04", "ubuntu-24.04-arm" ]
        debian-version: [
          "10",
          "11",
          "12"
        ]
    runs-on: ${{ matrix.os }}
    env:
      TAG_EXTENSION: "-debian${{matrix.debian-version}}-${{ contains(matrix.os, 'arm') && 'arm64' || 'amd64' }}"
      DEBIAN_VERSION: "${{matrix.debian-version}}"
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ secrets.ELASTIC_DOCKER_REGISTRY }}
          username: ${{ secrets.ELASTIC_DOCKER_USERNAME }}
          password: ${{ secrets.ELASTIC_DOCKER_PASSWORD }}

      - name: Docker build
        run: make -C ${{ env.MAKE_DIR }} build

      # TODO: uncomment when ready to push
      #- name: Docker push
      #  run: make -C ${{ env.MAKE_DIR }} push

      - name: Docker images
        run: docker images --format "table {{.Repository}}:{{.Tag}}\t{{.Size}}"
